In [1]:
#import stuff lol
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from scipy import stats
from scipy.stats.mstats import winsorize
from sklearn.feature_selection import SelectKBest, chi2

In [2]:
#setup csv variables
pA = pd.read_csv(r'C:/Code/SEC-101/Dido_transactions_A.csv') 
pB = pd.read_csv(r'C:/Code/SEC-101/Dido_transactions_B.csv')
oPA = pA.copy()
oPB = pB.copy()

In [3]:
#print the first 5 rows of A
pA.head()

   cust_id   Age         City  purchase_amount purchase_date payment_method
0     1037   NaN    New York          40.69000    2023-12-24         paypal
1     1045  21.0     new york        115.91000    2023-04-30           cash
2     1015   NaN      PHOENIX      16102.20503    2023-12-09           cash
3     1016  35.0     NEW YORK         74.87000    2023-12-25    Credit Card
4     1021   NaN  LOS ANGELES         13.97000    2023-08-24           Cash

In [4]:
#print the first 5 rows of B
pB.head(5)

   CustomerID  customer_age    city_name  amount_spent    txn_date pay_type
0        1018          74.0     Houston          58.09  2023-11-05     CASH
1        1036          26.0  Los Angeles           NaN  2023-10-06     CASH
2        1024          18.0          NaN        192.92  2023-11-24       CC
3        1050          58.0     Houston          28.30  2023-09-24     CASH
4        1029          52.0          NaN         10.69  2023-10-03     CASH

In [6]:
#rename columns in pB to match pA for merging
pB.rename(columns={
    "CustomerID": "cust_id", # this is key column for merging
    "customer_age": "Age",
    "city_name": "City",
    "amount_spent": "purchase_amount",
    "txn_date": "purchase_date",
    "pay_type": "payment_method",
}, inplace=True)
pB.head(5)

   cust_id   Age         City  purchase_amount purchase_date payment_method
0     1018  74.0     Houston             58.09    2023-11-05           CASH
1     1036  26.0  Los Angeles              NaN    2023-10-06           CASH
2     1024  18.0          NaN           192.92    2023-11-24             CC
3     1050  58.0     Houston             28.30    2023-09-24           CASH
4     1029  52.0          NaN            10.69    2023-10-03           CASH

In [33]:
#merges the two dataframes into one
mergedP = pd.merge(pA, pB, how='inner', on='cust_id')
mergedP.head(10)

,cust_id,Age_x,City_x,purchase_amount_x,purchase_date_x,payment_method_x,Age_y,City_y,purchase_amount_y,purchase_date_y,payment_method_y
0,1045,21.0,new york,115.91000,2023-04-30,cash,21.0,New York,NaN,2023-05-18,CC
1,1015,NaN,PHOENIX,16102.20503,2023-12-09,cash,37.0,phoenix,38.880,2023-10-26,CC
2,1015,NaN,PHOENIX,16102.20503,2023-12-09,cash,37.0,Phoenix,166.140,2023-01-24,PP
3,1016,35.0,NEW YORK,74.87000,2023-12-25,Credit Card,35.0,New York,NaN,2023-04-24,CASH
4,1016,35.0,NEW YORK,74.87000,2023-12-25,Credit Card,35.0,new york,186.070,2023-02-09,CC
5,1016,35.0,NEW YORK,74.87000,2023-12-25,Credit Card,35.0,NaN,146.900,2023-06-05,CC
6,1021,NaN,LOS ANGELES,13.97000,2023-08-24,Cash,18.0,NaN,111.816,2023-06-19,CC
7,1047,41.0,PHOENIX,425.19000,2023-06-05,Cash,41.0,phoenix,13.950,2023-05-17,NaN
8,1047,41.0,PHOENIX,425.19000,2023-06-05,Cash,41.0,PHOENIX,163.450,2023-12-13,CC
9,1056,31.0,Chicago,217.37000,2023-03-29,Credit Card,31.0,chicago,185.270,2023-09-30,CASH